#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * scripts/prerender.js
 * ──────────────────────
 * Tiny static pre-renderer for the Muk Buddy SPA. Runs AFTER
 * `react-scripts build` (see frontend package.json → build:blog).
 *
 * Why we need this:
 *   The CRA build emits a single `build/index.html` whose <body> only
 *   contains `<div id="root"></div>`. Non-JS crawlers (Bing, link-preview
 *   bots, AI search agents) see a blank page; /ads serves byte-identical
 *   HTML to /, so the two pages are not distinguishable in search results.
 *
 * What this script does:
 *   1. Boots a local static server on `build/`
 *   2. Drives headless Chrome (system google-chrome, via puppeteer-core)
 *      to load each route in the SPA
 *   3. Waits for React + react-helmet-async to render
 *   4. Captures the fully-rendered HTML and writes it back to
 *        build/index.html               (homepage)
 *        build/ads/index.html           (Meta-ads LP)
 *        build/thank-you/index.html     (form thank-you page)
 *
 *   Apache vhost serves whichever file matches the URL path. The blog
 *   pages were already statically generated by build-blog.js, so they're
 *   untouched here.
 *
 * Hydration:
 *   frontend/src/index.js conditionally calls hydrateRoot() when #root
 *   already has children. That keeps everything reactive after first
 *   paint — only the FIRST paint is the prerendered HTML.
 */

const fs = require("fs");
const path = require("path");
const http = require("http");
const handler = require("serve-handler"); // shipped with `serve`
const puppeteer = require("puppeteer-core");

const FRONTEND_DIR = path.join(__dirname, "..", "frontend");
const BUILD_DIR = path.join(FRONTEND_DIR, "build");
const PORT = process.env.PRERENDER_PORT || 5050;

// Routes to pre-render. Order matters: render `/` LAST so its overwrite
// of `build/index.html` doesn't pollute the static-server fallback used
// when puppeteer navigates to `/ads` or `/thank-you` (those routes don't
// have their own `build/<route>/index.html` until we write one).
const ROUTES = ["/ads", "/thank-you", "/about", "/"];

// Try to resolve a Chrome/Chromium binary. Production VPS may have a
// different path — set CHROME_PATH env var to override.
function findChromeExecutable() {
  if (process.env.CHROME_PATH && fs.existsSync(process.env.CHROME_PATH)) {
    return process.env.CHROME_PATH;
  }
  // Prefer the headless_shell from Playwright's bundle if available — it's
  // a stable known-good build. Fall back to system Chrome/Chromium.
  const candidates = [
    "/pw-browsers/chromium_headless_shell-1208/chrome-linux/headless_shell",
    "/usr/bin/google-chrome",
    "/usr/bin/google-chrome-stable",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
    "/snap/bin/chromium",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  ];
  return candidates.find((p) => fs.existsSync(p));
}

function routeToOutputPath(route) {
  if (route === "/") return path.join(BUILD_DIR, "index.html");
  const trimmed = route.replace(/^\/+|\/+$/g, "");
  return path.join(BUILD_DIR, trimmed, "index.html");
}

async function main() {
  if (!fs.existsSync(BUILD_DIR)) {
    console.error(
      `✗ build/ directory not found at ${BUILD_DIR}. Run \`yarn build\` first.`
    );
    process.exit(1);
  }

  // Snapshot the original CRA-built index.html shell. Some routes will
  // fall back to it via the static server while we render. If we let
  // each route overwrite it in turn, the next route would load the
  // previous one's prerendered DOM and Helmet would briefly mount the
  // wrong page's tags before settling — leaking title/canonical/og:url
  // duplicates into the captured HTML.
  const SHELL_PATH = path.join(BUILD_DIR, "index.html");
  const originalShell = fs.readFileSync(SHELL_PATH, "utf8");

  const chromePath = findChromeExecutable();
  if (!chromePath) {
    console.warn(
      "⚠ No Chrome/Chromium binary found. Skipping prerender. " +
        "Set CHROME_PATH env var to override. " +
        "Build still succeeds — but `/`, `/ads`, `/thank-you` will be " +
        "served as empty SPA shells until prerender runs in an env with Chrome."
    );
    process.exit(0); // Don't fail the build — just skip.
  }
  console.log(`✓ Using Chrome at ${chromePath}`);

  // ─── 1. Start static server on build/ ───
  const server = http.createServer((req, res) => {
    // Rewrite SPA fallback: for routes Apache would serve via DirectoryIndex
    // we need the local server to also resolve missing dirs back to /index.html
    // so puppeteer can hit each route and let React render it.
    return handler(req, res, {
      public: BUILD_DIR,
      rewrites: [{ source: "**", destination: "/index.html" }],
      cleanUrls: false,
    });
  });
  await new Promise((resolve) => server.listen(PORT, resolve));
  console.log(`✓ Static server up on http://localhost:${PORT}`);

  // ─── 2. Launch headless Chrome ───
  const browser = await puppeteer.launch({
    executablePath: chromePath,
    headless: "new",
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
    ],
  });

  try {
    for (const route of ROUTES) {
      const url = `http://localhost:${PORT}${route}`;
      const out = routeToOutputPath(route);
      console.log(`→ Rendering ${route} → ${path.relative(BUILD_DIR, out)}`);

      const page = await browser.newPage();
      // Tell client code it's running under prerender — useful if we ever
      // want to skip a side-effect (analytics fire, video autoplay, etc.).
      await page.setUserAgent("MukBuddyPrerender/1.0 puppeteer-core");
      await page.goto(url, { waitUntil: "networkidle0", timeout: 30000 });

      // Give react-helmet-async + any deferred rendering a final tick.
      await new Promise((r) => setTimeout(r, 600));

      const rawHtml = await page.content();
      // Post-process: replace the prerender-server URL with production so
      // baked-in tracking pixels (Meta, Google Ads) don't leak "localhost"
      // strings into the shipped HTML. Any pixel call the SDK made during
      // headless render includes url=http%3A%2F%2Flocalhost%3A5050%2F and
      // domain=localhost — swap for the production origin.
      const html = rawHtml
        .replace(/http%3A%2F%2Flocalhost%3A5050/g, "https%3A%2F%2Fmukbuddy.com")
        .replace(/http:\/\/localhost:5050/g, "https://mukbuddy.com")
        .replace(/domain=localhost/g, "domain=mukbuddy.com")
        .replace(/localhost:5050/g, "mukbuddy.com");
      // Restore the original CRA shell as the fallback for the NEXT route's
      // prerender. (Skip on the last route — `/` should keep its prerendered
      // content as the served index.html.)
      fs.mkdirSync(path.dirname(out), { recursive: true });
      fs.writeFileSync(out, html, "utf8");
      if (route !== "/") {
        fs.writeFileSync(SHELL_PATH, originalShell, "utf8");
      }
      console.log(`  ✓ wrote ${path.relative(FRONTEND_DIR, out)} (${html.length} bytes)`);
      // Defensive close — puppeteer-core 22 + chromium-1208 occasionally
      // throws "Connection closed" on Page.close() even after content() has
      // already returned cleanly. The captured HTML is safely on disk; we
      // swallow the close-error and continue to the next route.
      try {
        await page.close();
      } catch (closeErr) {
        console.log(`  (page.close warning, continuing: ${closeErr.message})`);
      }
    }
  } finally {
    try { await browser.close(); } catch (_) { /* same race, harmless */ }
    server.close();
  }

  console.log("✓ Prerender complete.");
}

main().catch((err) => {
  console.error("✗ Prerender failed:", err);
  process.exit(1);
});
